### ISSUE TITLE
Exercise 13.1 question?

### ISSUE THREAD

**Issue by UesugiErii** [brynhayder/reinforcement_learning_an_introduction#6]
your bellman equations:
![image](https://user-images.githubusercontent.com/24751316/81178949-8fb78400-8fdb-11ea-951d-72b06c556077.png)
I dont think that and the next f(p) is right, when agent in v1, if agent choose left, it will still stay in v1.
It should be
![image](https://user-images.githubusercontent.com/24751316/81179500-4f0c3a80-8fdc-11ea-9540-4e66007e3d1f.png)
then f(p) should be
![image](https://user-images.githubusercontent.com/24751316/81179650-8d095e80-8fdc-11ea-87af-2619bd9b2665.png)
![image](https://user-images.githubusercontent.com/24751316/81179816-c346de00-8fdc-11ea-8407-7ff711e7fc1a.png)
and the answer dont change, still is 2-sqrt(2)

**Comment by caikangli** [comment]
Here, I'm confused about why you only multiply p with v(1) or v(2), can you explain for that? In my opinion,  we should multiply p with (reward+v(1))。So we can get
![image](https://user-images.githubusercontent.com/29040094/81669793-481c7680-9479-11ea-8fe0-5730eccac2d4.png)
then the initial state values should be
![image](https://user-images.githubusercontent.com/29040094/81670053-a6495980-9479-11ea-864c-9feada2a2fc2.png)
and the answer also is 2-sqrt(2)

**Comment by UesugiErii** [comment]
@caikangli   
I think you are right，I did not notice v3 is also incorrect.
This is amazing that wrong and correct formula can get the same result.

**Comment by caikangli** [comment]
I calculate the result of my formula today when I make p=2-sqrt(2)。It is amazing that my result is -10.6 and is not same as the correct result -11.6。Then I see that its reward is all -1 for reach step！！！！！。So my formula should be modified as
![image](https://user-images.githubusercontent.com/29040094/81789974-516c1880-9537-11ea-8561-dc12e5132441.png)
and v(1) is
![image](https://user-images.githubusercontent.com/29040094/81790003-59c45380-9537-11ea-9cce-02118bf880f6.png)
Coincidentally, the result is also 2-sqrt(2)

**Comment by UesugiErii** [comment]
@caikangli 
2 days ago，I am wrong, in fact, v3 is right.
And then, your equation is the same as my original equation，but I calculated wrong v1.
Your v1 is right.
