### ISSUE TITLE
Exercise 9.1

### ISSUE THREAD

**Issue by hannagabor** [brynhayder/reinforcement_learning_an_introduction#7]
I think the solution for exercise 9.1 is not correct. If I understand it correctly, in that solution, our estimate would be the same for all the states.

My suggestion is that the feature vector should be an indicator of the state: the feature vector's length would be equal to the number of states, and `x(s_i)` would be a vector that contains `1` at the `i`th coordinate and `0` at the others. The weight vector would also have the same length as the number of states. The `i`th weight would be our value estimate for `s_i`. When we're doing the update, the gradient of `x(s_i)` is `0` everywhere except for the coordinate `i`, where it's `1`, so we would only update the weight for the current state.

**Comment by brynhayder** [comment]
Yep you're right, the features are a one-hot encoding on the states. The second sentence is a mistake. Thanks!
